### ISSUE TITLE
Jython 3 on GraalVM & Truffle?

### ISSUE THREAD

**Issue by oroppas** [jython/jython3#28]
Zippy (https://github.com/securesystemslab/zippy) has Python 3 implemented on
Truffle framework (https://github.com/graalvm/truffle). 

JRuby has Truffle with Sulong to run C extension
(http://chrisseaton.com/rubytruffle/llvm-cauldron-16/llvm-cauldron-sulong.pdf)

Is there any discussion on Jython following such path?

**Comment by Stewori** [comment]
Last time I looked at it, Zippy was still rather experimental. Does it actually allow to call Java API?

Sulong depends on GraalVM's FFI, while Jython wants to be runnable on the normal JVM. I'd actually like to explore alternative FFI options for [JyNI](https://github.com/Stewori/JyNI) 3, but I won't start that before [project panama](http://openjdk.java.net/projects/panama/) matures a bit, so I can design a coherent abstraction layer that takes all important FFIs into account.

Regarding C-extensions: Unfortunately TruffleC is not open, at least last time I looked. Anyway, running C-extension code on Graal- or J- VM does not yet bridge the gaps in API-design and GC/memory management between Jython and C-extensions written for CPython. I hope I can port that part from JyNI one day, but that's still rather hypothetic.

**Comment by oroppas** [comment]
Thanks for the info. I wasn't aware of JyNI & Project Panama. 

It's still not clear to me how JRuby + Sulong bridges the gaps in API design, GC, GIL, etc. for C-extensions. I speculated they'd already addressed the issue and Jython can reap the benefits but it sounds like the things are more complicated.

**Comment by Stewori** [comment]
I don't know sufficient detail about (J)Ruby's C-interface, maybe they just don't have these problems, or they solved them somehow. Impossible to tell without having a look at Truffle C (closed source (?))/studying Sulong in more detail (which I wouldn't have time for currently).

CPython's C-extension API is particularly JVM-unfriendly, because it exposes GC-API to C-extensions. It is common practice for C-extensions to adopt CPython's memory management model with ref-counting and relying on CPython's GC's reference cycle search. Regarding finalization behavior and weak references there are a couple of further subtle differences. In contrast to that JVM's JNI leaves memory management completely up to a JNI-extension and keeps JVM's GC-magic pretty much under the hood. This makes it difficult to serve Python C-extension's needs. See https://arxiv.org/abs/1607.00825 for further reading on this topic. Note that this article only scopes binary compatibility. By changing source/headers other approaches might be feasible, but the topic is then still hot and difficult (e.g. because subtle finalization and weakref differences still apply).

**Comment by isaiah** [comment]
@oroppas JRuby itself doesn't support cext, (it used to has an experimental support, but removed later), the one you talked about is the truffle branch, which is waiting for jdk 9 release. I personally like the way JRuby handles this problem, they created a easy to use java native extension interface, and encourage people to write bindings in java for the popular gem e.g. nokogiri, pg etc. Meanwhile I'm also looking forward to see how far we can push with JyNI. From my understanding, `project panama` is also most driven by the JRuby guys as the need to access platform APIs when implementing a language like ruby and python on JVM.
