### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by tghjnjvg** [jython/jython3#43]
jython有没有能支持android的呀 或者改一改jython的源码让它支持android jython开源的吗 源码哪里看呢

**Comment by stuaxo** [comment]
> Translation:
> 
> Does jython support android or change the source code of jython to make it support android jython open source? Where to look at the source code # 43
> 
> 

A.

According to the answer on Stackoverflow, Jython relies on using the Java Bytecode, since Android uses the Dalvik Virtual machine this will not work
https://stackoverflow.com/questions/11120130/programming-android-apps-in-jython

That answer is quite old though so maybe things have changed since 2012


根据关于Stackoverflow的回答，Jython依赖使用Java字节码，因为Android使用Dalvik虚拟机，所以这将无法工作
https://stackoverflow.com/questions/11120130/programming-android-apps-in-jython

**Comment by Stewori** [comment]
(The main issue is not dalvik, but the need to generate bytecode *at runtime*, see my comment https://stackoverflow.com/questions/11120130/programming-android-apps-in-jython#comment106675679_11120130. Otherwise one could in theory dex the generated code AOT.)
Also see https://sourceforge.net/p/jython/mailman/message/36752389/ and answers to https://github.com/jythontools/jython/issues/172.
